name: AtomMcContraband
main: me.thienbao860.plugin.contraband.AtomMcContraband
authors:
  - thienbao860
  - Frosty
version: "1.1"
commands:
  contraband:
    description: Contraband commands
    aliases: [contraband, contra]
    usage: /contraband